name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Download artifacts
        run: |
          aws s3 cp --recursive s3://by-secret-spot-artifacts/${{ github.sha }} ./artifacts
      - name: Prepare artifacts
        run: |
          cd artifacts
          for file in * ; do mv $file secret-spot-${file%.*}-${{ inputs.tag }}.${file#*.}; done
      - name: Show
        run: |
          ls -la artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
          files: ./artifacts/*

