name: Release
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Download artifacts
        run: |
          aws s3 cp --recursive s3://by-secret-spot-artifacts/${{ github.sha }} ./artifacts
      - name: Show
        run: |
          ls -la artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          files: ./artifacts/*

