name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'latest'
        required: true
jobs:
  schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Download artifacts
        run: |
          aws s3 cp --recursive s3://by-secret-spot-artifacts/${{ inputs.version }} artifacts
      - name: Show
        run: |
          ls -la artifacts
